DWAPlannerROS:
  max_vel_x: 3
  min_vel_x: -0.3
  max_vel_y: 0
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 0
  max_in_place_vel_theta: 0
  holonomic_robot: false

  acc_lim_theta: 1
  acc_lim_x: 3
  acc_lim_y: 0
  escape_vel: 0.8

  vx_samples: 20
  vtheta_samples: 20
  sim_time: 30

  path_distance_bias: 20

  yaw_goal_tolerance: 0.8

  xy_goal_tolerance: 0.3

  sim_granularity: 0.1

  occdist_scale: 0.05
