TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.4
  max_vel_y: 0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0
  max_in_place_vel_theta: 0
  holonomic_robot: false

  acc_lim_theta: 1.0
  acc_lim_x: 0.01
  acc_lim_y: 0
  escape_vel: 0.4

  sim_time: 10
