obstacle_range: 5 //机器人检测障碍物的最大范围
raytrace_range: 5 //传感器的最大探测距离
footprint: [[-0.14, 0.14], [0.14, 0.14], [0.14, -0.14], [-0.14, -0.14]]
inflation_radius: 1
cost_scaling_factor: 5
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}
