local_costmap:  
 global_frame: odom
 robot_base_frame: base_link
 update_frequency: 10.0
 publish_frequency: 2.0
 static_map: true
 rolling_window: true
 width: 4.0
 height: 6.0
 always_send_full_costmap: true
 resolution: 0.05
 meter_scoring: false
